### ISSUE TITLE
ClassLoader.getResource issue

### ISSUE THREAD

**Issue by tuschcarsten** [plasma-umass/doppio#375] opened 2015-08-21 20:34 UTC
Hi,
I am trying to run a jar with doppio. It seems to work well, except that I get a NullPointerException when trying to load resources from the class loader. The following works fine when executing the jar with java on my machine. However, when executing the jar with doppio, a NullPointerException is thrown by the getResource method:

    ClassLoader classLoader = obj.class.getClassLoader();
    URL libraryFolder = classLoader.getResource("library/");

The directory "library" is existing inside the jar file. Is loading Resources from jar files implemented?

**Comment by jvilk** [comment] 2015-08-21 22:12
Thanks for the report! Are you using the `master` branch, or the `new-objects` branch?

If I remember correctly, resources are a bit buggy. I was in the middle of investigating the issue in the `new-objects` branch before I had to turn my attention elsewhere for awhile. But now that someone else is encountering it... perhaps I will take another look tonight. :smile:

**Comment by tuschcarsten** [comment] 2015-08-22 05:35
To be honest, I had problems with building the code due to bower package compatibility issues. I am using the compiled version from the doppio-demo.

**Comment by jvilk** [comment] 2015-08-24 02:42
Resources almost certainly do not work on the demo code, since it's quite old!

The `new-objects` branch should work with resources, since we're properly using the OpenJDK's `AppClassLoader` for application-loaded JAR files. However, there's a serious performance regression... the JDK's `AppClassLoader` unzips JAR files in 100% Java, since we do not implement the native methods for unzipping.

This, and a few hard-to-stomp-out bugs, are the current holdup with us updating the demo with a new version. I need to hook up our JavaScript unzipper to the Java natives for unzipping. I'll update you here when the `new-objects` branch is ready for prime time.

**Comment by tuschcarsten** [comment] 2015-08-24 15:49
I tried to compile the new-objects code, but grunt produces the following error:

    doppio/vendor/DefinitelyTyped/node/node.d.ts(425,5): error TS1128: Declaration or statement expected.

Also, the continuous integration framework says that build is failing for the new-objects branch (https://github.com/plasma-umass/doppio/tree/new-objects).

Regarding the unzipping of JAR files, is there a chance that the performance is better if the archive is unzipped on the server? I could imagine that fetching every file via AJAX-request is also relatively slow.

**Comment by jvilk** [comment] 2015-08-24 16:08
> I tried to compile the new-objects code

Make sure you re-run `npm install` and `bower install` (and/or maybe `bower update`). `new-objects` has different dependencies than master.

Also, the *build* completes fine on the continuous integration framework, but a single *unit test* fails, causing the "build" to fail. I'm working on fixing that test.

> Regarding the unzipping of JAR files, is there a chance that the performance is better if the archive is unzipped on the server?

You can actually use JAR files where the class files are "stored" and not compressed in the JAR file. I don't have numbers concerning the overhead there, but the uncompressed Java Class Library is 100+MB in total (compresses to ~30MB total). Currently, we eagerly pull in all of the JAR files on the classpath, but there's support lurking in the class library itself to lazily pull in the JAR files as they are needed using a pre-produced index of classes in the JAR files.

As a stop-gap solution, maybe I should just have doppio grab the stored JAR files in a one-time setup stage, and cache them in browser-local storage.

> I could imagine that fetching every file via AJAX-request is also relatively slow.

Yes, fetching individual class files isn't too great, and isn't what you'd want to do in a production setting. That's why I put some effort into getting JAR file support up-to-snuff, and I'd like to get it working well once I squash some bugs in the `new-objects` branch.

As an aside, I was trying to use gzipped JAR files to take advantage of the browser's native gzip capabilities, but found out the hard way that it can only ungzip text data and not binary data. I'd have to do something incredibly inefficient to leverage the browser's gzip capabilities: Encode the JAR file in base64, gzip the base64 representation, and then get the base64'd data into a binary buffer somehow. Ugh.

Anyway, I apologize for the difficulties you're experiencing. Let me know how the `new-objects` branch works out for you, or if you continue to have difficulties!

**Comment by jvilk** [comment] 2015-08-24 18:01
I also just updated the version of the Java Class Library that `new-objects` uses, so you'll need to delete `vendor/java_home` before pulling, updating, and running.

(I should really have a nice way for the build system to check if that's out-of-date...)

**Comment by tuschcarsten** [comment] 2015-09-09 07:57
Thanks for you help! I finally was able to build the new-ojects branch without any errors.

**Comment by jvilk** [comment] 2015-09-12 23:00
Excellent! Let me know if you have any issues with resources (or anything else!) in that branch, as I'm prepping it for merger into master. I'll close this for now.

**Closed by jvilk** 2015-09-12 23:00 UTC
Labels: bug
