### ISSUE TITLE
doppioh problem

### ISSUE THREAD

**Issue by awcoding** [plasma-umass/doppio#479] opened 2016-10-02 05:09 UTC
I had a problem with generating a native stub method using doppioh. 

```shell
$ ./doppioh -classpath . -d natives/ classes/ns/Hello

/home/aw/doppio/node_modules/browserfs/dist/src/backend/ZipFS.ts:717
      cb(new ZipTOC(index, cdEntries, eocd, data));
      ^
Error: Callback was already called.
    at /home/aw/doppio/node_modules/async/dist/async.js:844:36
    at /home/aw/doppio/src/classpath.ts:105:17
    at Function.ZipFS.computeIndexResponsive (/home/aw/doppio/node_modules/browserfs/dist/src/backend/ZipFS.ts:717:7)
    at Immediate._onImmediate (/home/aw/doppio/node_modules/browserfs/dist/src/backend/ZipFS.ts:714:15)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```
PS ES6 Generators have started working for me lately in chrome. So I thought an approach like this (https://github.com/mozilla/task.js) might be of interest, for a potential solution to the browser api wrapping issue in doppio.

**Comment by jvilk** [comment] 2016-10-03 00:52
I have reproduced the issue; this looks like a bug.

**Comment by jvilk** [comment] 2016-10-03 01:03
Regarding `task.js`, I'm not sure what exactly you mean. Generators expose a nice interface that might be useful for a native API one day, since you can "pause" a JavaScript function to wait for a DoppioJVM function call to return. But it's not fruitful to pursue them as the default solution until they are present in all web browsers and are fast.

**Comment by jvilk** [comment] 2016-10-03 01:11
@awcoding you need to use a package name, not a class name. The error message should be fixed, though.

Try: `./doppioh -classpath . -d natives/ classes/ns`

**Closed** 2016-10-11 15:22 UTC
Labels: bug

**Comment by jvilk** [comment] 2016-10-11 15:35
@awcoding OK, I was wrong; the help text specified that class names should work. I found a bug that prevented it from working. This is now fixed in v0.4.2. Thanks for reporting!

**Comment by awcoding** [comment] 2016-10-11 19:45
Thanks for that. Sorry for the late response. I just got back from my vacation.

Is the change in master? I think there still might be an issue here. 

```shell
./doppio -classpath -d natives/ classes/ns/Hello
Encountered error: TypeError: Cannot read property 'getLoader' of undefined
TypeError: Cannot read property 'getLoader' of undefined
    at a.getLoader (/home/aw/doppio/src/threading.ts:705:49)
    at a.throwNewException (/home/aw/doppio/src/threading.ts:1155:54)
    at b.a.throwClassNotFoundException (/home/aw/doppio/src/ClassLoader.ts:340:12)
    at a.cb (/home/aw/doppio/src/ClassLoader.ts:553:14)
    at a.run (/home/aw/doppio/src/threading.ts:548:12)
    at a.run (/home/aw/doppio/src/threading.ts:847:12)
    at Immediate._onImmediate (/home/aw/doppio/src/threadpool.ts:83:16)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

BTW Regarding js generator support, I think it's in Chrome, FF & Microsoft Edge now. That's pretty good. I doubt it will get any better than that for the next 5 years.

**Comment by jvilk** [comment] 2016-10-11 20:03
> Is it meant to put more than:
> registerNatives({
> });
> in the file? That's all I get.

It will put that into a file if the classes you passed to `doppioh` have no native methods. Are you sure your target classes/packages have native methods?

> BTW Regarding js generator support, I think it's in Chrome, FF & Microsoft Edge now. That's pretty good. I doubt it will get any better than that for the next 5 years.

Oh, that's good progress. My next point still holds, though: They need to be relatively fast. I know that initial generator support limited their execution to JS interpreters, limiting their performance. The last I heard, FF and Chrome landed some initial JIT support, but the performance story isn't clear yet. I talked with the folks who work on Pyret who may evaluate a generator-based solution for their native JS functions; if it works out for them, maybe I'll look into using them in Doppio.

**Comment by awcoding** [comment] 2016-10-11 20:33
Oops, forgot my native keyword,. :)
